### ISSUE TITLE
Terminer les fichiers d'erreurs et les tester  pour les requêtes invalides

### ISSUE THREAD

**Issue by laghrish** [l3miage-bouvier5/l3-miage-example-spring#31]

**Comment by laghrish** [comment]
Get Un seul Miahoot : MiahootEntityNotFoundException (DONE)
Get plusieurs Miahoots : MiahootListEntityNotFoundException (DONE)
Supprimer Un seul Miahoot: MiahootEntityNotFoundException (DONE)
Supprimer plusieurs Miahoots : MiahootListEntityNotFoundException (DONE)

**Comment by l3miage-salouha** [comment]
post un Miahoot(meme userId et name) : MiahootAlreadyExist (DONE).
